apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - image:  supergiantkir/animals:bear
    name: test-container
    volumeMounts:
    - mountPath: /storage
      name: app-storage
  - image:  yanivomc/spring-music:latest
    name: test-container1
    volumeMounts:
    - mountPath: /storage
      name: app-storage
  volumes:
  - name:  app-storage
    hostPath:
      path: /tmp/files
      type: DirectoryOrCreate
