apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: ui
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
spec:
  containers:
  - image:  supergiantkir/animals:bear
    name: test-container
    volumeMounts:
    - mountPath: /storage
      name: app-storage
  - image:  yanivomc/spring-music:latest
    name: test-container1
    volumeMounts:
    - mountPath: /storage
      name: app-storage
  volumes:
  - name:  app-storage
    hostPath:
      path: /tmp/files
      type: DirectoryOrCreate
