kind: Service
apiVersion: v1
metadata:
  name: test-service
spec:
  selector:
    app: service
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8080
  clusterIP: 100.64.0.11
  type: LoadBalancer
