apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
spec:
  selector:
    matchLabels:
      app: service
  replicas: 2
  template:
    metadata:
      labels:
        app: service
    spec:
     containers:
     - name: service
       image: yanivomc/spring-music:latest
       ports:
       - containerPort: 8080
